apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflowsuccess-eventsource
spec:
  template:
    serviceAccountName: argoworkflow-eventsource-sa
  resource:
    downloadraw-success:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
      filter:
        afterStart: true
        labels:
          - key: component
            operation: ==
            value: "downloadraw"
          - key: workflows.argoproj.io/completed
            operation: ==
            value: "true"
    cleancmip6-success:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
      filter:
        afterStart: true
        labels:
          - key: component
            operation: ==
            value: "cleancmip6"
          - key: workflows.argoproj.io/completed
            operation: ==
            value: "true"
    dc6-success:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
      filter:
        afterStart: true
        labels:
          - key: component
            operation: ==
            value: "dc6"
          - key: workflows.argoproj.io/completed
            operation: ==
            value: "true"
