apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cildc6-org
spec:
  secretName: argo-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "argo.cildc6.org"
