apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: biascorrectdownscale
  labels:
    component: biascorrectdownscale
spec:
  workflowMetadata:
    labels:
      component: biascorrectdownscale
  entrypoint: with-jobs
  arguments:
    parameters:
      - name: jobs
        value: |
          [
            {
              "target": "ssp",
              "variable_id": "tasmax",
              "historical": {
                "activity_id": "CMIP",
                "experiment_id": "historical",
                "table_id": "day",
                "variable_id": "tasmax",
                "source_id": "GFDL-ESM4",
                "institution_id": "NOAA-GFDL",
                "member_id": "r1i1p1f1",
                "grid_label": "gr1",
                "version": "20190726"
              },
              "ssp": {
                "activity_id": "ScenarioMIP",
                "experiment_id": "ssp370",
                "table_id": "day",
                "variable_id": "tasmax",
                "source_id": "GFDL-ESM4",
                "institution_id": "NOAA-GFDL",
                "member_id": "r1i1p1f1",
                "grid_label": "gr1",
                "version": "20180701"
              }
            }
          ]
      - name: regrid-method
        value: "bilinear"
      - name: correct-wetday-frequency
        value: "false"
      - name: qdm-kind
        value: "additive"
  templates:


      # Loop through each job listed.
    - name: with-jobs
      inputs:
        parameters:
          - name: jobs
          - name: regrid-method
          - name: correct-wetday-frequency  # "true" or "false" STRING!
          - name: qdm-kind  # additive or multiplicative
      steps:
        - - name: parameterize
            template: parameterize
            arguments:
              parameters:
                - name: target
                  value: "{{ item.target }}"
                - name: historical
                  value: "{{ item.historical }}"
                - name: ssp
                  value: "{{ item.ssp }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: correct-wetday-frequency
                  value: "{{ inputs.parameters.correct-wetday-frequency }}"
                - name: qdm-kind
                  value: "{{ inputs.parameters.qdm-kind }}"
            withParam: "{{ inputs.parameters.jobs }}"


      # Start work for target simulation, with target-specific configs.
    - name: parameterize
      inputs:
        parameters:
          - name: target
          - name: ssp
          - name: historical
          - name: regrid-method
          - name: qdm-kind
          - name: correct-wetday-frequency
          - name: domainfile1x1
            value: "gs://support-c23ff1a3/domain.1x1.zarr"
          - name: domainfile0p25x0p25
            value: "gs://support-c23ff1a3/domain.0p25x0p25.zarr"
      steps:
        - - name: historical
            template: biascorrectdownscale
            arguments:
              parameters:
                - name: simulation
                  value: "{{ inputs.parameters.historical }}"
                - name: historical
                  value: "{{ inputs.parameters.historical }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: qdm-kind
                  value: "{{ inputs.parameters.qdm-kind }}"
                - name: correct-wetday-frequency
                  value: "{{ inputs.parameters.correct-wetday-frequency }}"
                - name: first-year
                  value: 1950
                - name: last-year
                  value: 2014
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
                - name: domainfile0p25x0p25
                  value: "{{ inputs.parameters.domainfile0p25x0p25 }}"
            when: "{{inputs.parameters.target}} == historical"
          - name: ssp
            template: biascorrectdownscale
            arguments:
              parameters:
                - name: simulation
                  value: "{{ inputs.parameters.ssp }}"
                - name: historical
                  value: "{{ inputs.parameters.historical }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: qdm-kind
                  value: "{{ inputs.parameters.qdm-kind }}"
                - name: correct-wetday-frequency
                  value: "{{ inputs.parameters.correct-wetday-frequency }}"
                - name: first-year
                  value: 2015
                - name: last-year
                  value: 2100
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
                - name: domainfile0p25x0p25
                  value: "{{ inputs.parameters.domainfile0p25x0p25 }}"
            when: "{{inputs.parameters.target}} == ssp"


    - name: biascorrectdownscale
      inputs:
        parameters:
          - name: simulation
          - name: historical
          - name: regrid-method
          - name: qdm-kind
          - name: correct-wetday-frequency
          - name: first-year
          - name: last-year
          - name: domainfile1x1
          - name: domainfile0p25x0p25
          - name: reference-zarr
            # Use simulation variable_id to get reference URL.
            value: >-
              gs://clean-b1dbca25/reanalysis/ERA-5/F320/{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}.1995-2015.F320.zarr
      dag:
        tasks:
          - name: get-input-clean-training-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "training"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.historical, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.historical, '$.grid_label')}}"
                - name: version
                  value: "{{=jsonpath(inputs.parameters.historical, '$.version')}}"
                - name: base-url
                  value: "gs://clean-b1dbca25/cmip6"
          - name: get-input-clean-simulation-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.experiment_id')}}"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.grid_label')}}"
                - name: version
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.version')}}"
                - name: base-url
                  value: "gs://clean-b1dbca25/cmip6"
          - name: get-output-biascorrected-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.experiment_id')}}"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.grid_label')}}"
                - name: version
                  value: "{{workflow.creationTimestamp.Y}}{{workflow.creationTimestamp.m}}{{workflow.creationTimestamp.d}}{{workflow.creationTimestamp.H}}{{workflow.creationTimestamp.M}}{{workflow.creationTimestamp.S}}"
                - name: base-url
                  value: "gs://biascorrected-492e989a/stage"
          - name: get-output-downscaled-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.experiment_id')}}"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.grid_label')}}"
                - name: version
                  value: "{{workflow.creationTimestamp.Y}}{{workflow.creationTimestamp.m}}{{workflow.creationTimestamp.d}}{{workflow.creationTimestamp.H}}{{workflow.creationTimestamp.M}}{{workflow.creationTimestamp.S}}"
                - name: base-url
                  value: "gs://downscaled-288ec5ac/stage"
          - name: biascorrect
            templateRef:
              name: qdm
              template: main
            depends: "get-input-clean-simulation-url && get-input-clean-training-url"
            arguments:
              parameters:
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: reference-zarr
                  value: "{{ inputs.parameters.reference-zarr }}"
                - name: training-zarr
                  value: "{{ tasks.get-input-clean-training-url.outputs.parameters.out-url }}"
                - name: simulation-zarr
                  value: "{{ tasks.get-input-clean-simulation-url.outputs.parameters.out-url }}"
                - name: out-zarr
                  value: "gs://scratch-170cd6ec/{{ workflow.uid }}/{{ pod.name }}/qdm-adjusted.zarr"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
                - name: correct-wetday-frequency
                  value: "{{ inputs.parameters.correct-wetday-frequency }}"
                - name: qdm-kind
                  value: "{{ inputs.parameters.qdm-kind }}"
                - name: first-year
                  value: "{{ inputs.parameters.first-year }}"
                - name: last-year
                  value: "{{ inputs.parameters.last-year }}"
          - name: rechunk-biascorrected
            depends: "get-output-biascorrected-url && biascorrect"
            templateRef:
              name: rechunk
              template: rechunk
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.biascorrect.outputs.parameters.out-zarr }}"
                - name: out-zarr
                  value: "{{ tasks.get-output-biascorrected-url.outputs.parameters.out-url }}"
                - name: time-chunk
                  value: 73
                - name: lat-chunk
                  value: 10
                - name: lon-chunk
                  value: 180
          - name: validate-biascorrected
            depends: rechunk-biascorrected
            templateRef:
              name: qualitycontrol-check-cmip6
              template: qualitycontrol-check-cmip6
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.rechunk-biascorrected.outputs.parameters.out-zarr }}"
                - name: variable
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: data
                  value: "bias_corrected"
                - name: time
                  value: >-
                    {{=jsonpath(inputs.parameters.simulation, '$.experiment_id') == 'historical' ? 'historical' : 'future'}}
          - name: create-fine-reference
            templateRef:
              name: qplad
              template: create-fine-reference
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ inputs.parameters.reference-zarr }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domain-file
                  value: "{{ inputs.parameters.domainfile0p25x0p25 }}"
          - name: create-coarse-reference
            templateRef:
              name: qplad
              template: create-coarse-reference
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ inputs.parameters.reference-zarr }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domainfile0p25x0p25
                  value: "{{ inputs.parameters.domainfile0p25x0p25 }}"
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
          - name: preprocess-biascorrected
            templateRef:
              name: qplad
              template: preprocess-biascorrected
            depends: rechunk-biascorrected
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.rechunk-biascorrected.outputs.parameters.out-zarr }}"
                - name: domain-file
                  value: "{{ inputs.parameters.domainfile0p25x0p25 }}"
          - name: qplad
            depends: >-
              get-output-downscaled-url
              && preprocess-biascorrected
              && create-coarse-reference
              && create-fine-reference
            templateRef:
              name: qplad
              template: qplad
            arguments:
              parameters:
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: simulation-zarr
                  value: "{{ tasks.preprocess-biascorrected.outputs.parameters.out-zarr }}"
                - name: coarse-reference-zarr
                  value: "{{ tasks.create-coarse-reference.outputs.parameters.out-zarr }}"
                - name: fine-reference-zarr
                  value: "{{ tasks.create-fine-reference.outputs.parameters.out-zarr }}"
                - name: qdm-kind
                  value: "{{ inputs.parameters.qdm-kind }}"
                - name: out-zarr
                  value: "{{ tasks.get-output-downscaled-url.outputs.parameters.out-url }}"
          - name: validate-downscaled
            depends: qplad
            templateRef:
              name: qualitycontrol-check-cmip6
              template: qualitycontrol-check-cmip6
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.qplad.outputs.parameters.out-zarr }}"
                - name: variable
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: data
                  value: "downscaled"
                - name: time
                  value: >-
                    {{=jsonpath(inputs.parameters.simulation, '$.experiment_id') == 'historical' ? 'historical' : 'future'}}
