# Downloads select, raw CMIP6 from GCP to co-located Azure storage for test case.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-cmip6
  labels:
    component: download-cmip6
spec:
  workflowMetadata:
    labels:
      component: download-cmip6
  entrypoint: main
  arguments:
    parameters:
      - name: variable-id
        value: "tasmin"
      - name: source-id
        value: "GFDL-ESM4"
      - name: historical
        value: |
          [
            { "activity-id": "CMIP", "experiment-id": "historical", "table-id": "day", "variable-id": "tasmin", "source-id": "GFDL-ESM4", "institution-id": "NOAA-GFDL", "member-id": "r1i1p1f1", "grid-label": "gr1", "version": "20190726" }
          ]
      - name: ssps
        value: |
          [
            { "activity-id": "ScenarioMIP", "experiment-id": "ssp370", "table-id": "day", "variable-id": "tasmin", "source-id": "GFDL-ESM4", "institution-id": "NOAA-GFDL", "member-id": "r1i1p1f1", "grid-label": "gr1", "version": "20180701" },
            { "activity-id": "ScenarioMIP", "experiment-id": "ssp245", "table-id": "day", "variable-id": "tasmin", "source-id": "GFDL-ESM4", "institution-id": "NOAA-GFDL", "member-id": "r1i1p1f1", "grid-label": "gr1", "version": "20180701" },
            { "activity-id": "ScenarioMIP", "experiment-id": "ssp126", "table-id": "day", "variable-id": "tasmin", "source-id": "GFDL-ESM4", "institution-id": "NOAA-GFDL", "member-id": "r1i1p1f1", "grid-label": "gr1", "version": "20180701" }
          ]
  templates:

    - name: main
      inputs:
        parameters:
          - name: variable-id
          - name: source-id
          - name: historical
          - name: ssps
      dag:
        tasks:
          - name: download-historical
            template: download-gcm
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{item.experiment-id}}"
                - name: activity-id
                  value: "{{item.activity-id}}"
                - name: table-id
                  value: "{{item.table-id}}"
                - name: variable-id
                  value: "{{item.variable-id}}"
                - name: source-id
                  value: "{{item.source-id}}"
                - name: institution-id
                  value: "{{item.institution-id}}"
                - name: member-id
                  value: "{{item.member-id}}"
                - name: grid-label
                  value: "{{item.grid-label}}"
                - name: version
                  value: "{{item.version}}"
                - name: out-url
                  value: "az://raw-cmip6/{{inputs.parameters.source-id}}/historical/{{inputs.parameters.variable-id}}.zarr"
            withParam: "{{ inputs.parameters.historical }}"
          - name: download-ssps
            template: download-gcm
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{item.experiment-id}}"
                - name: activity-id
                  value: "{{item.activity-id}}"
                - name: table-id
                  value: "{{item.table-id}}"
                - name: variable-id
                  value: "{{item.variable-id}}"
                - name: source-id
                  value: "{{item.source-id}}"
                - name: institution-id
                  value: "{{item.institution-id}}"
                - name: member-id
                  value: "{{item.member-id}}"
                - name: grid-label
                  value: "{{item.grid-label}}"
                - name: version
                  value: "{{item.version}}"
                - name: out-url
                  value: "az://raw-cmip6/{{inputs.parameters.source-id}}/{{item.experiment-id}}/{{inputs.parameters.variable-id}}.zarr"
            withParam: "{{ inputs.parameters.ssps }}"


    - name: download-gcm
      inputs:
        parameters:
          - name: experiment-id
          - name: activity-id
          - name: table-id
          - name: variable-id
          - name: source-id
          - name: institution-id
          - name: member-id
          - name: grid-label
          - name: version
          - name: out-url
      outputs:
        parameters:
          - name: out-zarr
            value: "{{ inputs.parameters.out-url }}"
      script:
        image: downscalecmip6.azurecr.io/dodola:0.5.0
        env:
          - name: ACTIVITY_ID
            value: "{{inputs.parameters.activity-id}}"
          - name: EXPERIMENT_ID
            value: "{{inputs.parameters.experiment-id}}"
          - name: TABLE_ID
            value: "{{inputs.parameters.table-id}}"
          - name: VARIABLE_ID
            value: "{{inputs.parameters.variable-id}}"
          - name: SOURCE_ID
            value: "{{inputs.parameters.source-id}}"
          - name: INSTITUTION_ID
            value: "{{inputs.parameters.institution-id}}"
          - name: MEMBER_ID
            value: "{{inputs.parameters.member-id}}"
          - name: GRID_LABEL
            value: "{{inputs.parameters.grid-label}}"
          - name: INTAKE_VERSION
            value: "{{inputs.parameters.version}}"
          - name: OUTPATH
            value: "{{inputs.parameters.out-url}}"
          - name: AZURE_STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: workerstoragecreds-secret
                key: azurestorageaccount
          - name: AZURE_STORAGE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: workerstoragecreds-secret
                key: azurestoragekey
        command: [python]
        source: |
          import os
          import intake
          import dodola.repository

          print("Searching catalog")
          col = intake.open_esm_datastore("https://storage.googleapis.com/cmip6/pangeo-cmip6.json")
          cat = col.search(
              activity_id=os.environ.get("ACTIVITY_ID"),
              experiment_id=os.environ.get("EXPERIMENT_ID"),
              table_id=os.environ.get("TABLE_ID"),
              variable_id=os.environ.get("VARIABLE_ID"),
              source_id=os.environ.get("SOURCE_ID"),
              member_id=os.environ.get("MEMBER_ID"),
              grid_label=os.environ.get("GRID_LABEL"),
              version=int(os.environ.get("INTAKE_VERSION")),
          )
          d = cat.to_dataset_dict(progressbar=False)
          k = list(d.keys())
          if len(k) != 1:
              raise ValueError("catalog does not have one entry, reconsider input IDs so only one entry")
          print(f"Found one catalog entry {k}")
          print(d)  # DEBUG

          dodola.repository.write(os.environ.get("OUTPATH"), d[k[0]])
        resources:
          requests:
            memory: 14Gi
            cpu: "200m"
          limits:
            memory: 14Gi
            cpu: "1000m"
      activeDeadlineSeconds: 1500
      retryStrategy:
        limit: 4
        retryPolicy: "Always"
