apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - biascorrectdownscale.yaml
  - catalog.yaml
  - clean-cmip6.yaml
  - clean-era5.yaml
  - distributed-regrid.yaml
  - download-cmip6.yaml
  - qualitycontrol-check-cmip6.yaml
  - rechunk.yaml
  - regrid.yaml
  - zarr-transfer.yaml
