apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: qualitycontrol-check-cmip6
  annotations:
    workflows.argoproj.io/description: >-
      Automated quality-control check for CMIP6 data at various stages of dc6.

      Input Zarr Store locations are specified with fsspec-style URLs. These
      checks are specific to the Downscaling CMIP6 project.
    workflows.argoproj.io/tags: zarr,qualitycontrol,cmip6,validate,dc6
    workflows.argoproj.io/version: '>= 3.1.0'
  labels:
    component: qualitycontrol
spec:
  entrypoint: qualitycontrol-check-cmip6
  arguments:
    parameters:
      - name: in-zarr
        value: "gs://downscaled-288ec5ac/stage/ScenarioMIP/NOAA-GFDL/GFDL-ESM4/ssp370/r1i1p1f1/day/tasmax/gr1/v20211022013318.zarr"
      # Must be "tasmax", "tasmin", "dtr", "pr".
      - name: variable
        value: "tasmax"
      # Must be "downscaled", "biascorrected", "cmip6".
      - name: data
        value: "downscaled"
      # Must be "future" or "historical".
      - name: time
        value: "future"
  workflowMetadata:
    labels:
      component: qualitycontrol
  templates:

    - name: qualitycontrol-check-cmip6
      inputs:
        parameters:
          - name: in-zarr
          - name: variable
          - name: data
          - name: time
      container:
        image: us-central1-docker.pkg.dev/downscalecmip6/private/dodola:dev
        command: [ "dodola" ]
        args:
          - "validate-dataset"
          - "{{ inputs.parameters.in-zarr }}"
          - "--variable={{ inputs.parameters.variable }}"
          - "--data-type={{ inputs.parameters.data }}"
          - "--time-period={{ inputs.parameters.time }}"
        resources:
          requests:
            memory: 8Gi
            cpu: "2000m"
          limits:
            memory: 8Gi
            cpu: "2000m"
      activeDeadlineSeconds: 3600
