apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: regrid
  annotations:
    workflows.argoproj.io/description: >-
      Templates to regrid a small xarray Zarr Store in-memory, given an fsspec URL.
    workflows.argoproj.io/tags: fsspec,regrid,zarr,xarray
    workflows.argoproj.io/version: '>= 3.1.0'
  labels:
    component: utils
spec:
  templates:

    - name: regrid
      inputs:
        parameters:
          - name: in-zarr
          - name: out-zarr
            value: "gs://scratch-170cd6ec/{{ workflow.uid }}/{{ pod.name }}/out.zarr"
          - name: regrid-method
          - name: domain-file
      outputs:
        parameters:
          - name: out-zarr
            value: "{{ inputs.parameters.out-zarr }}"
      container:
        image: ghcr.io/climateimpactlab/dodola:0.8.0
        command: [ "dodola" ]
        args:
          - "regrid"
          - "{{ inputs.parameters.in-zarr }}"
          - "--astype=float32"
          - "--out"
          - "{{ inputs.parameters.out-zarr }}"
          - "--method"
          - "{{ inputs.parameters.regrid-method }}"
          - "--domain-file"
          - "{{ inputs.parameters.domain-file }}"
        resources:
          requests:
            memory: 48Gi
            cpu: "1000m"
          limits:
            memory: 48Gi
            cpu: "2000m"
      activeDeadlineSeconds: 3600
      retryStrategy:
        limit: 2
        retryPolicy: "Always"
