# Rough permissions needed to trigger an argo workflow from an argo-events sensor.
# See https://argoproj.github.io/argo-events/service-accounts/#service-account-for-sensors
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argoworkflow-trigger-role
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - workflows
    verbs:
      - create
      - list
