# Permissions to watch argo workflows in a namespace.
# See https://github.com/argoproj/argo-events/blob/master/examples/event-sources/resource.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argoworkflow-eventsource-role
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
